name: deenlink
description: "An All-in-one Islamic Application."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  adhan: ^2.0.0+1
  cached_network_image: ^3.4.1
  cookie_jar: ^4.0.9
  cupertino_icons: ^1.0.8
  dio: ^5.11.0
  dio_cookie_manager: ^3.5.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_ios_preview: ^1.0.0
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^11.0.0
  go_router: ^13.0.0
  google_fonts: ^8.1.0
  iconsax_flutter: ^1.0.0
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  shimmer: ^3.0.0
  shimmer_animation: ^2.2.2+1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
